// new Promise((resolve, reject) => {
//     console.log(3);
//     if (4===2) {
//       resolve("Promise resolved successfully");
//     } else {
//       reject("Promise rejected with an error");
//     }
//   })
//     .then((result) => {
//       console.log("Resolved:", result);
//     })
//     .catch((err) => {
//       console.log("Rejected:", err);
//     });
 


console.log(c);
let a=10

const b=9
var  c=2
